nome = input("Qual seu nome? ")
idade = input("Qual sua idade: ")
telefone = input("Digite seu telefone: ")
eMail = input("Digite seu e-mail: ")

print("---------------------------") 
print("Seja bem vinda,", nome, ".") 
print("Você tem", idade, "anos.")
print("Seu telefone é:", telefone, ".")
print("E seu e-mail é:", eMail, ".")
print("---------------------------") 